version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ofd
      MYSQL_DATABASE: ofd
      MYSQL_USER: ofd
      MYSQL_PASSWORD: ofd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  backend-app:
    build: .
    container_name: backend_app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/ofd
      SPRING_DATASOURCE_USERNAME: ofd
      SPRING_DATASOURCE_PASSWORD: ofd
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
